/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicButton: typeof import('./../components/basicButton/index.vue')['default']
    ButtonIcon: typeof import('./../components/buttonIcon/index.vue')['default']
    Cover: typeof import('./../components/cover/index.vue')['default']
    EmptyData: typeof import('./../components/emptyData/index.vue')['default']
    Icon: typeof import('./../components/Icon/index.vue')['default']
    ItemIndex: typeof import('./../components/TitleInfo/itemIndex.vue')['default']
    PlayButton: typeof import('./../components/playButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideRail: typeof import('./../components/slideRail/index.vue')['default']
    SongCard: typeof import('./../components/songCard/index.vue')['default']
    SongInfo: typeof import('./../components/songInfo/index.vue')['default']
    Switch: typeof import('./../components/switch/index.vue')['default']
    Text: typeof import('./../components/text/index.vue')['default']
    TitleInfo: typeof import('./../components/TitleInfo/index.vue')['default']
  }
}
